### PR TITLE
I've made a lot of changes, and you may need to check them out in advance.

### PR DESCRIPTION
**Pull request by larryw3i**
I've made a lot of changes, and you may need to check them out in advance. @alejandroautalan 
fix1: failed to open the .ui file.
I failed to open this [.ui file](https://github.com/alejandroautalan/pygubu-designer/blob/master/pygubudesigner/ui/about_dialog.ui) use pygubu-designer.
https://github.com/alejandroautalan/pygubu/pull/248
Screenshot from 2021-08-23 19-49-08

fix2:
  File "/home/larry/fun/larryw3i/pygubu/venv/bin/pygubu-designer", line 33, in <module>
    sys.exit(load_entry_point('pygubu-designer==0.17', 'gui_scripts', 'pygubu-designer')())
  File "/home/larry/fun/larryw3i/pygubu/venv/bin/pygubu-designer", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/larry/fun/larryw3i/pygubu/venv/lib/python3.9/site-packages/pygubudesigner/main.py", line 48, in <module>
    from .uitreeeditor import WidgetsTreeEditor
  File "/home/larry/fun/larryw3i/pygubu/venv/lib/python3.9/site-packages/pygubudesigner/uitreeeditor.py", line 42, in <module>
    from pygubudesigner import preferences as pref
  File "/home/larry/fun/larryw3i/pygubu/venv/lib/python3.9/site-packages/pygubudesigner/preferences.py", line 22, in <module>
    from appdirs import AppDirs
~~ModuleNotFoundError: No module named 'appdirs'~~  
**It's not these output, I seem to have forgotten them: appdirs is not defined~.**

https://github.com/alejandroautalan/pygubu-designer/compare/master...larryw3i:master#diff-e24d04a11f7f3c3d5cc630d2be4cd895073345ae38362e10c82b37c667a71033L22-L27

https://github.com/alejandroautalan/pygubu-designer/compare/master...larryw3i:master#diff-e24d04a11f7f3c3d5cc630d2be4cd895073345ae38362e10c82b37c667a71033L34-L36

https://github.com/alejandroautalan/pygubu-designer/compare/master...larryw3i:master#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L148

add1: on_warranty_click
https://github.com/alejandroautalan/pygubu-designer/compare/master...larryw3i:master#diff-b5ac53294fe3407bcdad76ea480be76f57f666dc41d8e3bd67687792636a1922R661-R668

other: pygubudesigner/propertieshelp.py--> use translator _
. . .and some bash scripts

### CODE REVIEW

**Comment by larryw3i** [comment]
https://github.com/larryw3i/pygubu/commit/22f6630d0708827a4fe1fc463bbb105a4228ebc9  also.

**Comment by larryw3i** [comment]
@alejandroautalan That's all,  please check these commits if you have time and I will be glad if you are willing to merge them.

**Comment by larryw3i** [comment]
Well, I'll just commit so many.

**Comment by larryw3i** [comment]
https://github.com/larryw3i/pygubu/commit/aa8857e897919661a7acd34f9ac5dc8eb7558f4b  
[pygubu](https://github.com/larryw3i/pygubu/commit/aa8857e897919661a7acd34f9ac5dc8eb7558f4b)  has also been changed.

**Comment by alejandroautalan** [comment]
Great, thanks for your work.

Greetings
Alejandro A.

**Pull request merged**
